### ISSUE TITLE
hoppers don't collect items

### ISSUE THREAD

**Issue by zgrzebcio** [Dark-Arcana/Speedy-Hoppers#10]
i use speedyhoppers-1.15.2-1 and no work collecting items
![2020-02-02_21 11 05](https://user-images.githubusercontent.com/13418993/73614618-1b96ca00-4601-11ea-8c4f-8f4c82eac709.png)

**Comment by ghost** [comment]
Can confirm, i'll try to get this sorted soon

**Comment by ghost** [comment]
Should be fixed now in v1.15.2-2. The version indicates it's for 1.15.2, but it should work for 1.15.1 as well
