### ISSUE TITLE
Potentially Dangerous alternative prefix `speedyhoppers` for name `speedyhopper_mk1`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.

### ISSUE THREAD

**Issue by bloodconfetti** [Dark-Arcana/Speedy-Hoppers#4]
Hello there! In my latest log there shows some warnings about your mod.
[latest.log](https://github.com/al132mc/Speedy-Hoppers/files/3493393/latest.log)

**Comment by al132mc** [comment]
Many mods have this warning, not an issue, won't fix

**Comment by ghost** [comment]
This one actually has me a bit stumped because if I change the prefix to minecraft it gives me the exact opposite message i.e. ```Potentially Dangerous alternative prefix `minecraft` for name ... expected `speedyhoppers` ```

**Comment by ghost** [comment]
That being said, it /should/ be harmless

**Comment by ghost** [comment]
Fixed in 1.14.4-1.0.4
