### ISSUE TITLE
No Support for Hopper Minecarts

### ISSUE THREAD

**Issue by klugemonkey** [Dark-Arcana/Speedy-Hoppers#6]
Doesn't work with Minecarts.  Doesn't pull from normal hopper minecarts, nor can you create a speedy-hopper minecart.

**Comment by ghost** [comment]
I probably won't ever add speedy hopper minecarts, but I would expect them to be able to pull out of vanilla minecrafts. Please tell me exactly which version you are using

**Comment by ghost** [comment]
I'm going to merge this issue with https://github.com/al132mc/Speedy-Hoppers/issues/7 - closing this one
