### ISSUE TITLE
Game crashes when placed under certain blocks from other mods

### ISSUE THREAD

**Issue by Grox999** [Dark-Arcana/Speedy-Hoppers#9]
Found a bug when building a redstone machine where whenever I placed a speedy hopper (diamond tier) underneath a crystal chest from the Iron Chests mod and above a ranged proxy from the CapabilityProxy mod, the game crashes. I'm running Minecraft 1.14.4, Forge 28.1.75, and am running the latest version of your mod. I haven't seen if the game only crashes when the hopper is placed above the proxy block or underneath the chest, so it could be either one or both of them simultaneously causing problems.

**Comment by ghost** [comment]
Could you please give me a crash log?

**Comment by ghost** [comment]
I'm no longer supporting 1.14, but if anyone is experiencing this on 1.16 feel free to open a new issue.
